config/routes.rb
Rails.application.routes.draw do

  resources :courses do
    resources :instructors do
      resources :course_materials do
      end
    end
  end

  root 'courses#index'

end

app/models/course_material.rb
# == Schema Information
#
# Table name: course_materials
#
#  id                   :integer          not null, primary key
#  title                :string
#  description          :string
#  course_instructor_id :integer
#  file_file_name       :string
#  file_content_type    :string
#  file_file_size       :integer
#  file_updated_at      :datetime
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#

class CourseMaterial < ActiveRecord::Base
  has_attached_file :file
  
  do_not_validate_attachment_file_type :file

  validates_attachment_content_type :file, :content_type => /\/(?!(php|pl|exe|pm|cfm|asp)$)/

  belongs_to :course_instructor
end

app/controllers/course_materials_controller.rb
class CourseMaterialsController < ApplicationController
  before_action :set_course_material, only: [:show, :edit, :update, :destroy]

  before_action :set_course
  before_action :set_instructor
  before_action :set_course_instructor

  protect_from_forgery with: :null_session

  # GET /course_materials
  # GET /course_materials.json
  def index
    course_materials = @course_instructor.course_materials

    @course_materials = []

    course_materials.each do |course_material|
      @course_materials  << {
        id: course_material.id,
        title: course_material.title,
        description: course_material.description,
        course_instructor_id: course_material.course_instructor_id,
        course_id: course_material.course_instructor.course_id,
        instructor_id: course_material.course_instructor.instructor_id,
        filename: course_material.file_file_name,
        file_link: course_material.file.url,
        file: nil
      }
    end

    render json: @course_materials
  end

  # GET /course_materials/1
  # GET /course_materials/1.json
  def show
  end

  # GET /course_materials/new
  def new
    @course_material = CourseMaterial.new
  end

  # GET /course_materials/1/edit
  def edit
  end

  # POST /course_materials
  # POST /course_materials.json
  def create
    @course_material = @course_instructor.course_materials.new(course_material_params)

    
    if @course_material.save
      render json: @course_material, status: :created
    else
      render json: @course_material.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /course_materials/1
  # PATCH/PUT /course_materials/1.json
  def update
  #   respond_to do |format|
  #     if @course_material.update(course_material_params)
  #       format.html { redirect_to @course_material, notice: 'Course material was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @course_material }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @course_material.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

    if @course_material.update(course_material_params)
      render json: @course_material
    else
      render json: @course_material.errors, status: :unprocessable_entity
    end
  end

  # DELETE /course_materials/1
  # DELETE /course_materials/1.json
  def destroy
    @course_material.destroy

    render json: {}
    # respond_to do |format|
    #   format.html { redirect_to course_materials_url, notice: 'Course material was successfully destroyed.' }
    #   format.json { head :no_content }
    # end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course_material
      @course_material = CourseMaterial.find(params[:id])
    end

    def set_course
      @course = Course.find(params[:course_id]).decorate
    end

    def set_instructor
      @instructor = Instructor.find(params[:instructor_id]).decorate
    end

    def set_course_instructor
      @course_instructor = CourseInstructor.where(course: @course, instructor: @instructor).first
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_material_params
      puts "AA"*100
      puts params
      puts "VV"*100
      params.require(:course_material).permit(:title, :description, :file)
    end
end

app/helpers/course_materials_helper.rb
module CourseMaterialsHelper
end

app/views/course_materials/_form.html.erb
<%= form_for [@course, @instructor, @course_material] do |f| %>
  <% if @course_material.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course_material.errors.count, "error") %> prohibited this course_material from being saved:</h2>

      <ul>
      <% @course_material.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :file %>
    <%= f.file_field :file %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/course_materials/edit.html.erb
<h1>Editing Course Material</h1>

<%= render 'form' %>

<%= link_to 'Show', @course_material %> |
<%= link_to 'Back', course_materials_path %>

app/views/course_materials/index.html.erb
<p id="notice"><%= notice %></p>

<strong> Page: </strong>
<%= link_to 'Home', '/' %> /
<%= link_to @course.name, course_path(@course) %> /
<%= link_to @instructor.full_name, course_instructor_path(@course, @instructor) %> /
Course Material Listing

<h1>Listing Course Materials</h1>


<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>File</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @course_materials.each do |course_material| %>
      <tr>
        <td><%= course_material.title %></td>
        <td><%= course_material.description %></td>
        <td><img style="width: 150px;" src=<%= course_material.file.url %>/></td>
        <td><%= link_to 'Show', course_instructor_course_material_path(@course, @instructor, course_material) %></td>
        <td><%= link_to 'Edit', edit_course_instructor_course_material_path(@course, @instructor, course_material) %></td>
        <td><%= link_to 'Destroy', [@course, @instructor, course_material], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Course material', new_course_instructor_course_material_path %>

app/views/course_materials/new.html.erb
<strong> Page: </strong>
<%= link_to 'Home', '/' %> /
<%= link_to @course.name, course_path(@course) %> /
<%= link_to @instructor.full_name, course_instructor_path(@course, @instructor) %> /
New Course Material
<hr/>


<h1>New Course Material</h1>

<%= render 'form' %>

app/views/course_materials/show.html.erb
<p id="notice"><%= notice %></p>

<strong> Page: </strong>
<%= link_to 'Home', '/' %> /
<%= link_to @course.name, course_path(@course) %> /
<%= link_to @instructor.full_name, course_instructor_path(@course, @instructor) %> /
<%= @course_material.title %>
<hr/>


<p>
  <strong>Title:</strong>
  <%= @course_material.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @course_material.description %>
</p>

<%= link_to 'Edit', edit_course_instructor_course_material_path(@course, @instructor, @course_material) %> |
<%= link_to 'Back', course_instructor_course_materials_path %>