config/routes.rb
Rails.application.routes.draw do

  resources :courses do
    resources :instructors do
      resources :course_materials do
      end
    end
  end

  root 'courses#index'

end

app/models/instructor.rb
# == Schema Information
#
# Table name: instructors
#
#  id         :integer          not null, primary key
#  last_name  :string
#  first_name :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Instructor < ActiveRecord::Base
  has_many :course_instructors
  has_many :courses, through: :course_instructors
end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
  before_action :set_instructor, only: [:show, :edit, :update, :destroy]

  before_action :set_course
  before_action :set_course_instructor, only: [:show]

  # GET /instructors
  # GET /instructors.json
  def index
    @instructors = @course.instructors

    render json: @instructors
  end

  # GET /instructors/1
  # GET /instructors/1.json
  def show
    render json: @instructor
  end

  # GET /instructors/new
  def new
    @instructor = Instructor.new
  end

  # GET /instructors/1/edit
  def edit
  end

  # POST /instructors
  # POST /instructors.json
  def create
    @instructor = @course.instructors.create(instructor_params)

    respond_to do |format|
      if !@instructor.new_record?
        format.html { redirect_to course_instructors_path(@course), notice: 'Instructor was successfully created.' }
        format.json { render :show, status: :created, location: @instructor }
      else
        format.html { render :new }
        format.json { render json: @instructor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /instructors/1
  # PATCH/PUT /instructors/1.json
  def update
    respond_to do |format|
      if @instructor.update(instructor_params)
        format.html { redirect_to [@course, @instructor], notice: 'Instructor was successfully updated.' }
        format.json { render :show, status: :ok, location: @instructor }
      else
        format.html { render :edit }
        format.json { render json: @instructor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instructors/1
  # DELETE /instructors/1.json
  def destroy
    @instructor.destroy
    respond_to do |format|
      format.html { redirect_to course_instructors_url, notice: 'Instructor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_instructor
      @instructor = Instructor.find(params[:id]).decorate
    end

    def set_course
      @course = Course.find(params[:course_id]).decorate
    end

    def set_course_instructor
      @course_instructor = CourseInstructor.where(course: @course, instructor: @instructor).first
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def instructor_params
      params.require(:instructor).permit(:last_name, :first_name)
    end
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/views/instructors/_form.html.erb
<%= form_for [@course, @instructor] do |f| %>
  <% if @instructor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@instructor.errors.count, "error") %> prohibited this instructor from being saved:</h2>

      <ul>
      <% @instructor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/instructors/edit.html.erb
<h1>Editing Instructor</h1>

<%= render 'form' %>

<%= link_to 'Show', [@course, @instructor]  %> |
<%= link_to 'Back', course_instructors_path %>

app/views/instructors/index.html.erb
<p id="notice"><%= notice %></p>

<strong> Page: </strong>
<%= link_to 'Home', '/' %> /
<%= link_to @course.name, course_path(@course) %> / Instructor Listing

<hr/>

<h1>Listing Instructors</h1>

<table>
  <thead>
    <tr>
      <th>Last name</th>
      <th>First name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @instructors.each do |instructor| %>
      <tr>
        <td><%= instructor.last_name %></td>
        <td><%= instructor.first_name %></td>
        <td><%= link_to 'Show', [@course, instructor] %></td>
        <td><%= link_to 'Edit', [:edit, @course, instructor] %></td>
        <td><%= link_to 'Destroy', [@course, instructor], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Instructor', new_course_instructor_path(@course) %>

app/views/instructors/new.html.erb
<strong> Page: </strong>
<%= link_to 'Home', '/' %> /
<%= link_to @course.name, course_path(@course) %> / New Instructor
<hr/>

<h1>New Instructor</h1>


<%= render 'form' %>

<%= link_to 'Back', course_instructors_path(@course) %>

app/views/instructors/show.html.erb
<p id="notice"><%= notice %></p>

<strong> Page: </strong>
<%= link_to 'Home', '/' %> /
<%= link_to @course.name, course_path(@course) %> /
<%= @instructor.full_name %>

<hr/>

<p>
  <strong>Last name:</strong>
  <%= @instructor.last_name %>
</p>

<p>
  <strong>First name:</strong>
  <%= @instructor.first_name %>
</p>

<% course_mats=@course_instructor.course_materials %>
<strong>Course Materials (<%= course_mats.count %>) :</strong>

<% if course_mats.count > 0 %>
  <br/>
  <br/>
  <table>
    <thead>
      <tr>
        <th>Title</th>
        <th>Description</th>
        <th>File</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% course_mats.each do |course_material| %>
        <tr>
          <td><%= course_material.title %></td>
          <td><%= course_material.description %></td>
          <td><img style="width: 150px;" src=<%= course_material.file.url %>/></td>
          <td><%= link_to 'Show', course_instructor_course_material_path(@course, @instructor, course_material) %></td>
          <td><%= link_to 'Edit', edit_course_instructor_course_material_path(@course, @instructor, course_material) %></td>
          <td><%= link_to 'Destroy', [@course, @instructor, course_material], method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<br/>

<br/>

<br/>

<%= link_to 'Add New Course Material', new_course_instructor_course_material_path(@course, @instructor) %> |
<%= link_to 'Edit', edit_course_instructor_path(@course, @instructor) %> |
<%= link_to 'Back', course_instructors_path(@course) %>