config/routes.rb
Rails.application.routes.draw do

  resources :courses do
    resources :instructors do
      resources :course_materials do
      end
    end
  end

  root 'courses#index'

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  protect_from_forgery with: :null_session

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all

    render json: @courses
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
    render json: @course
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    # --------------
    # MODE: WEB APP
    # ---------------
    # respond_to do |format|
    #   if @course.save
    #     format.html { redirect_to @course, notice: 'Course was successfully created.' }
    #     format.json { render :show, status: :created, location: @course }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @course.errors, status: :unprocessable_entity }
    #   end
    # end

    # ----------
    # MODE: API
    # ----------
    if @course.save
      render json: @course, status: :created, location: @course
    else
      render json: @course.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    # --------------
    # MODE: WEB APP
    # ---------------
    # respond_to do |format|
    #   if @course.update(course_params)
    #     format.html { redirect_to @course, notice: 'Course was successfully updated.' }
    #     format.json { render :show, status: :ok, location: @course }
    #   else
    #     format.html { render :edit }
    #     format.json { render json: @course.errors, status: :unprocessable_entity }
    #   end
    # end

    # --------------
    # MODE: API
    # ---------------
    if @course.update(course_params)
      render json: @course
    else
      render json: @course.errors, status: :unprocessable_entity
    end

  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.delete

    render json: {}

    # --------------
    # MODE: WEB APP
    # ---------------
    # respond_to do |format|
    #   format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
    #   format.json { head :no_content }
    # end


  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id]).decorate
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:name, :title)
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form' %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>View Courses</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.name %></td>
        <td><%= course.title %></td>
        <td><%= link_to 'Show', course %></td>
        <td><%= link_to 'Edit', edit_course_path(course) %></td>
        <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Course', new_course_path %>

app/views/courses/new.html.erb
<strong> Page: </strong>
<%= link_to 'Home', '/' %> /
New Course
<hr/>


<h1>New Course</h1>

<%= render 'form' %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<strong> Page: </strong>
<%= link_to 'Home', '/' %> /
<%= link_to @course.name, course_path(@course) %> /
<hr/>

<p>
  <strong>Name:</strong>
  <%= @course.name %>
</p>

<p>
  <strong>Title:</strong>
  <%= @course.title %>
</p>

<p>
  <strong>Instructors:</strong>
  <table>
    <tbody>
    <% @course.instructors.each do |instructor| %>
      <tr>
        <td>
          <%= link_to instructor.last_name, [@course, instructor] %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</p>

<%= link_to 'Create Instructor', new_course_instructor_path(@course) %>

<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>